### PR TITLE
Android fb

### PR DESCRIPTION
**Pull request by brentgracey**
android

### CODE REVIEW

**Comment by myFree** [comment]
CAN WE MOVE THIS ALONG (this is a comment on the Dev FB; not the glob branch)

**Comment by myFree** [comment]
asdfasdfasdfdsf

**Comment by myFree** [comment]
asdfasdfasdfasdf

**Comment by myFree** [comment]
first comment

**Comment by myFree** [comment]
2nd comment

**Comment by myFree** [comment]
3rd comment

**Comment by myFree** [comment]
a

**Comment by brentgracey** [comment]
a

**Comment by brentgracey** [comment]
b

**Pull request merged**
